name: EstraPearls
main: net.estra.EstraPearls.PearlPlugin
version: 1.0
depend: [CivModCore]
commands:
  debug:
    usage: "/debug"
  forcefree:
    usage: "/forcefree <player>"
    description: "Admin only command, forcibly frees a pearl."
  ep:
    usage: "/ep"
    description: "Displays a friendly help menu."
  epfree:
    usage: "/epfree"
    description: "Frees the pearl you hold in your hand."
  pearl:
    usage: "/pearl <player>"
    description: "Pearls the player you specify."
  eplocate:
    usage: "/eplocate <player>"
    description: "Gives the location the pearled player is held at."